# Generated by Django 4.2.1 on 2023-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'MPESA')], default='cash', max_length=50),
        ),
    ]
